-- SQL Seeding Script for Toy Shop E-Commerce Database (PostgreSQL)

-- Clean existing seed data
DELETE FROM "Admins";
DELETE FROM "Payments";
DELETE FROM "OrderItems";
DELETE FROM "Orders";
DELETE FROM "Addresses";
DELETE FROM "Customers";
DELETE FROM "ProductImages";
DELETE FROM "Products";
DELETE FROM "Categories";

-- Insert Toy Categories
INSERT INTO "Categories" ("Id", "Name", "Description", "CreatedBy") VALUES
(1, 'Action Figures', 'Superheroes, robots, and battle figurines', 'Seed'),
(2, 'Educational & STEM', 'Toys that promote learning, logic, and creativity', 'Seed'),
(3, 'Board Games & Puzzles', 'Family board games and jigsaw puzzles for all ages', 'Seed'),
(4, 'Dolls & Playsets', 'Fashion dolls, dollhouses, and character playsets', 'Seed'),
(5, 'Building & Construction', 'Blocks, building bricks, and engineering sets', 'Seed');

-- Reset category sequence (since we explicitly set IDs)
SELECT setval(pg_get_serial_sequence('"Categories"', 'Id'), coalesce(max("Id"), 1)) FROM "Categories";

-- Insert Products
INSERT INTO "Products" ("Id", "CategoryId", "Name", "Description", "Price", "StockQuantity", "IsActive", "CreatedBy") VALUES
(1, 1, 'Galactic Defender Mech Suit', 'A 12-inch fully articulable robot action figure with light and sound effects.', 1499.00, 25, TRUE, 'Seed'),
(2, 1, 'Shadow Ninja Strike Figure', 'Poseable ninja action figure with dual swords and stealth cloak.', 499.00, 50, TRUE, 'Seed'),
(3, 2, 'RoboCoder Coding Kit', 'Introduce kids to computer logic with this screen-free coding companion robot.', 2499.00, 15, TRUE, 'Seed'),
(4, 2, 'Eco-Logic Weather Station Set', 'Perform experiments to learn about cloud formation, acid rain, and global warming.', 899.00, 30, TRUE, 'Seed'),
(5, 3, 'Kingdom Quest Board Game', 'A cooperative fantasy role-playing board game for 2-4 players.', 1299.00, 12, TRUE, 'Seed'),
(6, 3, '3D Solar System Jigsaw Puzzle', 'A 500-piece spherical puzzle forming a realistic model of our sun and planets.', 799.00, 40, TRUE, 'Seed'),
(7, 4, 'Bella the Baker Dollhouse Set', 'A 14-inch poseable doll with a mini bakery counter and 15 pretend baking accessories.', 1199.00, 18, TRUE, 'Seed'),
(8, 4, 'Royal Castle Wooden Playset', 'A foldable wooden princess castle with figures, horse carriage, and furniture.', 1899.00, 10, TRUE, 'Seed'),
(9, 5, 'Space Launch Heavy Rocket Blocks', 'A 850-piece building brick set to build a space launch vehicle and launchpad.', 2999.00, 20, TRUE, 'Seed'),
(10, 5, 'Master Engineer Gear & Motor Set', 'Contains gears, pulleys, axles, and a battery-operated motor to build 10 different moving machines.', 1799.00, 15, TRUE, 'Seed');

-- Reset products sequence
SELECT setval(pg_get_serial_sequence('"Products"', 'Id'), coalesce(max("Id"), 1)) FROM "Products";

-- Insert Product Images (Using reliable public domain placeholder-style illustration URLs)
INSERT INTO "ProductImages" ("ProductId", "ImageUrl", "CreatedBy") VALUES
(1, 'https://images.unsplash.com/photo-1530685934402-d5528b8de361?q=80&w=600&auto=format&fit=crop', 'Seed'),
(1, 'https://images.unsplash.com/photo-1546776310-eef45dd6d63c?q=80&w=600&auto=format&fit=crop', 'Seed'),
(2, 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=600&auto=format&fit=crop', 'Seed'),
(3, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=600&auto=format&fit=crop', 'Seed'),
(4, 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=600&auto=format&fit=crop', 'Seed'),
(5, 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=600&auto=format&fit=crop', 'Seed'),
(6, 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=600&auto=format&fit=crop', 'Seed'),
(7, 'https://images.unsplash.com/photo-1559251606-c623743a6d76?q=80&w=600&auto=format&fit=crop', 'Seed'),
(8, 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600&auto=format&fit=crop', 'Seed'),
(9, 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=600&auto=format&fit=crop', 'Seed'),
(10, 'https://images.unsplash.com/photo-1530685934402-d5528b8de361?q=80&w=600&auto=format&fit=crop', 'Seed');

-- Insert default admin user:
-- Username: admin
-- Password: admin123
-- Hash generated by BCrypt.Net-Next 4.2.0 (work factor 11) - verified correct
INSERT INTO "Admins" ("Username", "PasswordHash", "FullName", "CreatedBy") VALUES
('admin', '$2a$11$zdIOXd8mrAKnOKjl7HBEv.i96LsZcnbVIHLsE9aPeHoONS88phxgu', 'Toy Shop Administrator', 'Seed');

